# Generated by Django 4.2.5 on 2023-09-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='prof_pic/')),
                ('email', models.TextField(max_length=20)),
                ('phone', models.TextField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=15)),
                ('adress', models.TextField(max_length=40)),
                ('adress_2', models.TextField(blank=True, help_text='Optional', max_length=40, null=True)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
