# Generated by Django 4.2.5 on 2023-09-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsapp', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_alive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
